// Autogenerated Prebuilt Voice Audio Previews Map
// All voice samples are pre-generated and stored in /public/audio/previews/
// Users listen to built-in previews instantly with ZERO API latency and ZERO token usage.

export const PREBUILT_VOICE_PREVIEWS: Record<string, string> = {
  "voice_17raj9ewke3g": "/audio/previews/voice_17raj9ewke3g.wav",
  "aziza-ai": "/audio/previews/aziza-ai.wav",
  "madina-journalist": "/audio/previews/madina-journalist.wav",
  "dilnoza-blogger": "/audio/previews/dilnoza-blogger.wav",
  "zarina-culture": "/audio/previews/zarina-culture.wav",
  "nodira-analyst": "/audio/previews/nodira-analyst.wav",
  "malika-tech": "/audio/previews/malika-tech.wav",
  "jasur-business": "/audio/previews/jasur-business.wav",
  "charon-history": "/audio/previews/charon-history.wav",
  "otabek-comedy": "/audio/previews/otabek-comedy.wav",
  "ulugbek-history": "/audio/previews/ulugbek-history.wav",
  "farrux-tech": "/audio/previews/farrux-tech.wav",
  "bobur-coach": "/audio/previews/bobur-coach.wav",
  "puck-comedy": "/audio/previews/puck-comedy.wav",
  "kore-warm": "/audio/previews/kore-warm.wav",
  "fenrir-mystery": "/audio/previews/fenrir-mystery.wav",
  "zephyr-tech": "/audio/previews/zephyr-tech.wav",
  "aoede-poetic": "/audio/previews/aoede-poetic.wav"
};

/**
 * Returns static audio preview URL for a given voiceId, or undefined if not prebuilt
 */
export function getVoicePreviewUrl(voiceId: string): string | undefined {
  if (PREBUILT_VOICE_PREVIEWS[voiceId]) {
    return PREBUILT_VOICE_PREVIEWS[voiceId];
  }
  // Try fallback to standard pattern
  return `/audio/previews/${voiceId}.wav`;
}
