// Autogenerated Prebuilt Voice Audio Previews Map
// All voice samples are pre-generated and stored in /public/audio/previews/
// Users listen to built-in previews instantly with ZERO API latency and ZERO token usage.

export const PREBUILT_VOICE_PREVIEWS: Record<string, string> = {
  "voice_17raj9ewke3g": "/audio/previews/voice_17raj9ewke3g.wav",
  "aziza-ai": "/audio/previews/aziza-ai.wav",
  "madina-journalist": "/audio/previews/madina-journalist.wav",
  "dilnoza-blogger": "/audio/previews/dilnoza-blogger.wav",
  "zarina-culture": "/audio/previews/zarina-culture.wav",
  "nodira-analyst": "/audio/previews/nodira-analyst.wav",
  "malika-tech": "/audio/previews/malika-tech.wav",
  "jasur-business": "/audio/previews/jasur-business.wav",
  "charon-history": "/audio/previews/charon-history.wav",
  "otabek-comedy": "/audio/previews/otabek-comedy.wav",
  "ulugbek-history": "/audio/previews/ulugbek-history.wav",
  "farrux-tech": "/audio/previews/farrux-tech.wav",
  "bobur-coach": "/audio/previews/bobur-coach.wav",
  "sevara-science": "/audio/previews/sevara-science.wav",
  "javohir-media": "/audio/previews/javohir-media.wav",
  "sanjar-radio": "/audio/previews/sanjar-radio.wav",
  "sherzod-investigation": "/audio/previews/sherzod-investigation.wav",
  "shahnoza-speech": "/audio/previews/shahnoza-speech.wav",
  "rayhon-art": "/audio/previews/rayhon-art.wav",
  "gulzoda-edu": "/audio/previews/gulzoda-edu.wav",
  "eldor-fintech": "/audio/previews/eldor-fintech.wav",
  "umida-health": "/audio/previews/dilnoza-blogger.wav",
  "nigora-stories": "/audio/previews/rayhon-art.wav",
  "feruza-family": "/audio/previews/sevara-science.wav",
  "bekzod-sport": "/audio/previews/otabek-comedy.wav",
  "alisher-cyber": "/audio/previews/farrux-tech.wav",
  "rustam-agro": "/audio/previews/jasur-business.wav",
  "puck-comedy": "/audio/previews/sanjar-radio.wav",
  "kore-warm": "/audio/previews/shahnoza-speech.wav",
  "fenrir-mystery": "/audio/previews/sherzod-investigation.wav",
  "zephyr-tech": "/audio/previews/sevara-science.wav",
  "aoede-poetic": "/audio/previews/rayhon-art.wav"
};

/**
 * Returns static audio preview URL for a given voiceId, or undefined if not prebuilt
 */
export function getVoicePreviewUrl(voiceId: string): string | undefined {
  if (PREBUILT_VOICE_PREVIEWS[voiceId]) {
    return PREBUILT_VOICE_PREVIEWS[voiceId];
  }
  // Try fallback to standard pattern
  return `/audio/previews/${voiceId}.wav`;
}
